var cust=require('./customeModules.js');
var path=require('path');
console.log(cust.customeModuleMethod2());
console.log(cust.customeModuleMethod1());
var student=require('./customeModuleWithClass.js');
var student1=new student("Khairu",10);
student1.greeting();
console.log(path.basename(__filename));
console.log(path.dirname(__filename));
console.log(path.parse(__filename).base);
console.log(path.join(__dirname,'test','hello.html'));